name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main  # 设定部署的分支

permissions:
  contents: write  # Ensure GITHUB_TOKEN has write permission to contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --config-file mcgae_io/mkdocs.yml --remote-branch gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
